//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long TasksID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime TaskStartTime { get; set; }
        public System.DateTime TaskTrackedTime { get; set; }
    }
}
